# Template file - DO NOT put real secrets here
# Use scripts/generate-secrets.sh to create the actual secrets file
apiVersion: v1
kind: Secret
metadata:
  name: blog-secrets
  namespace: blog-app
type: Opaque
data:
  # No secrets needed for static content blog
  # This file is kept for future extensibility
