apiVersion: v1
kind: Service
metadata:
  name: blog-service
  namespace: blog-app
  labels:
    app: blog-app
spec:
  selector:
    app: blog-app
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP