apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-postgres-pvc
  namespace: blog-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 20Gi