name: Deploy Infrastructure

on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'infra/**'
  #     - '.github/workflows/deploy-infra.yaml'
  workflow_dispatch:
    inputs:
      stack:
        description: "Pulumi stack to deploy"
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

permissions:
  id-token: write
  contents: read

jobs:
  deploy-infra:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest

    env:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      ARM_USE_OIDC: true
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup node env
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Pulumi
        uses: pulumi/actions@v6

      - name: Install dependencies
        working-directory: ./infra
        run: npm install

      - name: Select Pulumi stack
        working-directory: ./infra
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            STACK="${{ github.event.inputs.stack }}"
          else
            STACK="prod"
          fi
          echo "Deploying stack: $STACK"
          echo "STACK_NAME=$STACK" >> $GITHUB_ENV

      - name: Preview infrastructure changes
        uses: pulumi/actions@v6
        with:
          command: preview
          work-dir: ./infra
          stack-name: ${{ env.STACK_NAME }}

      - name: Deploy infrastructure
        id: pulumi
        uses: pulumi/actions@v6
        with:
          command: up
          work-dir: ./infra
          stack-name: ${{ env.STACK_NAME }}

      - name: Add pulumi outputs to summary
        run: |
          echo "### Pulumi Stack Outputs ###" >> $GITHUB_STEP_SUMMARY
          echo "APP_SERVICE_NAME=$(steps.pulumi.outputs.appServiceName)" >> $GITHUB_STEP_SUMMARY
          echo "RESOURCE_GROUP=$(steps.pulumi.outputs.resourceGroupName)" >> $GITHUB_STEP_SUMMARY